---
# error prevention
# ----------------
- name: check variable prtg_device_id
  ansible.builtin.fail:
    msg: "host variable 'prtg_device_id' has to be defined in order to check the prtg device status"
  when: prtg_device_id is undefined

# check monitoring
# ----------------
# check prtg monitoring of device if 'check_monitoring' was specified
- name: "check if state of devices is 'up' in prtg"
  include_tasks: check_prtg.yml
  when: "'check_monitoring' in tasks"

# pause monitoring
# ----------------
# pause prtg monitoring of device if 'pause_monitoring' was specified
- name: "pause prtg monitoring for devices"
  include_tasks: pause_prtg.yml
  when: "'pause_monitoring' in tasks"

# resume monitoring
# ----------------
# resume prtg monitoring of device if 'resume_monitoring' was specified
- name: "resume prtg monitoring for devices"
  include_tasks: resume_prtg.yml
  when: "'resume_monitoring' in tasks"
