---
- name: verify that there are no snapshots
  hosts: all
  tasks:
    - name: verify that there are no snapshots
      hyperv_check_snapshots:
        vmname: "{{ hyperv_vmname }}"
        state: "absent"
      delegate_to: "{{ module_hyperv_host }}"
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_scheme: https
        ansible_winrm_port: 5986
        ansible_winrm_transport: credssp
        ansible_user: "{{ windows_admin_username }}"
        ansible_password: "{{ windows_admin_password }}"
