---
# playbook to install a specific KB

- name: Install only particular updates based on the KB numbers
   hosts: all
   tasks:

- name: Install only particular updates based on the KB numbers
   debug:
      msg: "Logfile in c:\\windows\\temp\\automated-patching.txt"
  ansible.windows.win_updates:
    category_name: '*'
    accept_list:
    - KB5003671
   log_path: c:\windows\temp\automated-patching.txt
   register: update_result
   until: update_result.found_update_count == 0                     
