---
- hosts: all
  tasks:
    # check if prtg monitoring of device is green ("up")
    - name: check monitoring status
      include_role:
        name: prtg
      vars:
        tasks:
          - check_monitoring

    # check free disk space
    - name: check free disk space
      include_role:
        name: windows_checks
      vars:
        tasks:
          - check_diskspace

    # pause monitoring for prtg device
    - name: "pause monitoring for device {{ inventory_hostname }}"
      include_role:
        name: prtg
      vars:
        tasks:
          - pause_monitoring

    # resume monitoring for prtg device
    - name: "resume monitoring for device {{ inventory_hostname }}"
      include_role:
        name: prtg
      vars:
        tasks:
          - resume_monitoring
