---
- hosts: all
  tasks:
    # check if prtg monitoring of device is green ("up")
    - name: check monitoring status
      include_role:
        name: prtg
      vars:
        tasks:
          - check_monitoring
          - pause_monitoring
